<template>
  <Snowf
    :amount="100"
    :size="5"
    :speed="1.5"
    :wind="0"
    :opacity="0.8"
    :swing="1"
    :image="null"
    :zIndex="null"
    :resize="true"
    color="#fff"
  />
</template>